Repository mosn/mosn, pull requests merged in 2018-07, with the labels that each got.

#26 Fix ci
  .gitignore
  .travis.yml
  Gopkg.lock
  Makefile
  README.md
  etc/script/report.sh
Labels: kind/devops, priority/P1

#28 fix #25 part3 fix mosn's all underscores
  pkg/api/v2/types.go
  pkg/config/convertxds.go
  pkg/filter/accept/originaldst/originaldst.go
  pkg/filter/accept/originaldst/types.go
  pkg/router/types.go
  pkg/server/handler.go
  pkg/stream/http/stream.go
  pkg/stream/http2/stream.go
  pkg/tests/scenetest/scene_bolt2http2_test.go
  pkg/tests/scenetest/scene_clientclose_test.go
  pkg/tests/scenetest/scene_http2_test.go
  pkg/tests/scenetest/scene_httpproxy_test.go
  pkg/tests/scenetest/scene_serverclose_test.go
  pkg/tests/scenetest/scene_sofarpc_test.go
  pkg/tests/scenetest/scene_v2bolt2http2_test.go
  pkg/tests/scenetest/util_common_test.go
  pkg/tests/scenetest/util_config_test.go
  pkg/types/network.go
  pkg/upstream/cluster/subsetlbimpl.go
Labels: area/codestyle, kind/enhancement

#10 [*] use jsonitor-go instead of encoding/json and tidy up vendor
  pkg/config/config.go
  pkg/config/dumper.go
  pkg/config/parser.go
  pkg/config/parser_test.go
  pkg/xds/xdsclient.go
  test/scenetest/util_config_test.go
Labels: kind/enhancement, priority/P2

#49 Ci cron job
  .travis.yml
  Makefile
  build/ci/.travis.yml
Labels: kind/test, status/done
