Repository mosn/mosn, pull requests merged in 2019-08, with the labels that each got.

#752 support goaway for http1
  pkg/stream/http/connpool.go
  pkg/stream/http/stream.go
Labels: cla:yes, size/M

#754 version 0.6.0
  VERSION
  docs/CHANGELOG.md
Labels: cla:yes, size/M

#770 close feature #769
  cmd/mosn/main/control.go
  pkg/mosn/starter.go
  pkg/mtls/sds/sdsclient.go
  pkg/types/xds.go
  pkg/xds/v2/adssubscriber.go
  pkg/xds/v2/cdssubscriber.go
  pkg/xds/v2/default_handler.go
  pkg/xds/v2/edssubscriber.go
  pkg/xds/v2/ldssubscriber.go
  pkg/xds/v2/rdssubscriber.go
  pkg/xds/v2/rdssubscriber_test.go
  pkg/xds/v2/types.go
  pkg/xds/xdsclient.go
Labels: area/xds, cla:yes, kind/feature, priority/P0, size/L

#776 modify mosn start logic
  pkg/mosn/starter.go
  pkg/xds/xdsclient.go
Labels: cla:yes, size/M

#771 add timeout log
  pkg/proxy/downstream.go
Labels: cla:yes, size/S

#773 sofa stream should reset when write error
  pkg/stream/sofarpc/stream.go
Labels: cla:yes, question, size/S

#775 fix memleak when upstream no response
  pkg/stream/sofarpc/stream.go
Labels: bug, cla:yes, question, size/S

#774 listener support restart
  pkg/network/idlechecker_test.go
  pkg/network/listener.go
  pkg/network/listener_test.go
  pkg/server/adapter.go
  pkg/server/adapter_test.go
  pkg/server/handler.go
  pkg/types/network.go
Labels: cla:yes, size/L

#749 support log roller by configuration
  pkg/admin/server/server_test.go
  pkg/api/v2/types.go
  pkg/log/README.md
  pkg/log/accesslog.go
  pkg/log/errorlog.go
  pkg/log/errorlog_test.go
  pkg/log/logger.go
  pkg/log/logger_manager_test.go
  pkg/log/logger_test.go
  pkg/log/roller.go
  pkg/log/roller_test.go
  pkg/server/server.go
  pkg/trace/sofa/log.go
Labels: cla:yes, size/L

#750 enhance get pool
  examples/codes/sofarpc-sample/client.go
  examples/codes/tcpproxy-sample/rpc_client.go
  pkg/api/v2/types.go
  pkg/network/connection.go
  pkg/network/connection_test.go
  pkg/network/idlechecker.go
  pkg/stream/http/stream_test.go
  pkg/stream/sofarpc/mock_test.go
  pkg/types/loadbalancer.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/cluster/host.go
  pkg/upstream/cluster/lb_register_test.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
  test/metrics/client.go
  test/util/rpc.go
  test/util/x_example.go
Labels: cla:yes, size/L

#745 add netBufferPool
  pkg/network/connection.go
Labels: First-time contributor, cla:yes, size/S

#778 add tls peek timeout
  examples/codes/sofarpc-sample/client.go
  examples/codes/tcpproxy-sample/rpc_client.go
  pkg/api/v2/types.go
  pkg/config/parser.go
  pkg/filter/network/tcpproxy/proxy.go
  pkg/mosn/starter.go
  pkg/mtls/conn.go
  pkg/mtls/mock_test.go
  pkg/mtls/tls_context_manager.go
  pkg/network/connection.go
  pkg/network/connection_test.go
  pkg/server/handler.go
  pkg/stream/client.go
  pkg/stream/http/connpool.go
  pkg/stream/http2/connpool.go
  pkg/stream/sofarpc/connpool.go
  pkg/stream/sofarpc/keepalive_test.go
  pkg/stream/types.go
  pkg/stream/xprotocol/connpool.go
  pkg/types/network.go
  pkg/types/tls.go
  pkg/xds/conv/convertxds.go
  test/metrics/client.go
  test/util/rpc.go
  test/util/x_example.go
Labels: cla:yes, size/L

#782 add metrics process time
  pkg/metrics/downstream.go
  pkg/metrics/store.go
  pkg/proxy/downstream.go
  pkg/proxy/stats.go
Labels: cla:yes, size/M

#777 Add: mq config
  pkg/api/v2/types.go
  pkg/config/configmanager.go
  pkg/config/configmanager_test.go
Labels: First-time contributor, cla:yes, size/L

#786 fix http header handle in retry
  pkg/stream/http/stream.go
  pkg/stream/http2/stream.go
  test/integrate/case.go
  test/integrate/retry_test.go
Labels: bug, cla:yes, size/M

#787 Temporary remove gzip support for prometheus sink
  pkg/metrics/sink/prometheus/prometheus.go
Labels: cla:yes, size/S

#791 fix panic when connection remoteaddr is nil
  pkg/network/connection.go
  pkg/network/connection_test.go
Labels: bug, cla:yes, question, size/S

#785 fix repo
  docs/Introduction.md
Labels: First-time contributor, bug, cla:yes, size/XS

#792 fix metadata nil check
  pkg/router/base_rule.go
  pkg/router/base_rule_test.go
  pkg/upstream/cluster/subset_loadbalancer.go
Labels: bug, cla:yes, size/M

#794 Add: mq config data
  pkg/api/v2/types.go
  pkg/config/configmanager.go
  pkg/config/configmanager_test.go
Labels: cla:yes, size/L

#796 version 0.7.0
  VERSION
  docs/CHANGELOG.md
Labels: cla:yes, size/S
