Repository mosn/mosn, pull requests merged in 2019-12, with the labels that each got.

#895 fix get app_name key
  pkg/protocol/sofarpc/models/constants.go
Labels: bug, cla:yes, size/XS

#905 fix write hang
  pkg/network/connection.go
Labels: bug, cla:yes, size/XS

#902 fix unit test
  pkg/upstream/cluster/cluster_adapter.go
  pkg/upstream/cluster/cluster_manager.go
  test/integrate/filter/reroute_test.go
  test/integrate/functiontest/keepalive_test.go
  test/integrate/functiontest/update_streamfilter_test.go
Labels: bug, cla:yes, size/M

#907 fix unit test
  pkg/log/logger_test.go
  test/integrate/filter/reroute_test.go
Labels: bug, cla:yes, size/XS

#909 fix from pr #901
  pkg/mosn/starter.go
  pkg/protocol/rpc/sofarpc/mapping.go
  pkg/proxy/proxy.go
  pkg/upstream/cluster/cluster_adapter.go
  pkg/upstream/cluster/cluster_manager.go
Labels: bug, cla:yes, size/S

#790 Feature gate handle func
  cmd/mosn/main/control.go
  pkg/featuregate/feature_gate.go
  pkg/featuregate/feature_gate_test.go
  pkg/featuregate/testdata_feature_gate.go
Labels: First-time contributor, cla:yes, size/L

#890 fix mosn example image
  build/contrib/builder/image/Dockerfile
  configs/mosn_config.json
  etc/supervisor/mosn.conf
  etc/supervisor/supervisord.conf
Labels: bug, cla:yes, size/L

#915 fix memleak when proxy goroutine panic
  pkg/proxy/downstream.go
  pkg/proxy/proxy.go
Labels: bug, cla:yes, question

#881 new test framework
  test/cases/direct_response/boltv1_test.go
  test/cases/direct_response/http1_test.go
  test/cases/run_all.sh
  test/cases/simple/boltv1_convert_test.go
  test/cases/simple/boltv1_test.go
  test/cases/simple/http1_test.go
  test/lib/basic.go
  test/lib/http/client.go
  test/lib/http/handler.go
  test/lib/http/request.go
  test/lib/http/server.go
  test/lib/http/types.go
  test/lib/mosn.go
  test/lib/sofarpc/boltv1_client.go
  test/lib/sofarpc/boltv1_server.go
  test/lib/sofarpc/client.go
  test/lib/sofarpc/server.go
  test/lib/sofarpc/types.go
Labels: cla:yes, kind/test, size/XXL

#877 pkg/xds: some simple code optimizations.
  pkg/xds/v2/cdssubscriber.go
  pkg/xds/v2/edssubscriber.go
  pkg/xds/v2/ldssubscriber.go
  pkg/xds/v2/rdssubscriber.go
  pkg/xds/xdsclient.go
Labels: First-time contributor, cla:yes, size/S

#885 pkg/xds/v2: add StreamClientMutex.
  pkg/xds/v2/adssubscriber.go
  pkg/xds/v2/types.go
  pkg/xds/xdsclient.go
Labels: First-time contributor, cla:yes, size/M
