Repository mosn/mosn, pull requests merged in 2019-10, with the labels that each got.

#832 add log
  pkg/network/connection.go
  pkg/network/connection_test.go
  pkg/sync/workerpool.go
Labels: cla:yes, size/S

#833 re support bolt v2
  pkg/protocol/rpc/sofarpc/codec/boltv2.go
Labels: cla:yes, size/M

#836 fix concurrent for proxy timeout
  pkg/proxy/downstream.go
Labels: bug, cla:yes, size/XS

#837 Fix/config dump concur
  pkg/config/configmanager.go
  pkg/config/configmanager_test.go
  pkg/config/constant_test.go
  pkg/config/dumper.go
  pkg/config/load_config.go
Labels: bug, cla:yes, size/L

#839 add connection state
  pkg/network/connection.go
  pkg/network/connection_test.go
  pkg/types/network.go
Labels: cla:yes, size/M

#841 change store map to pointer
  pkg/upstream/cluster/host.go
Labels: size/XS

#848 fix read buffer maybe zero
  pkg/buffer/iobuffer.go
Labels: bug, cla:yes, size/XS

#840 caller cell
  pkg/protocol/sofarpc/models/constants.go
  pkg/trace/sofa/rpc/ext/boltv1.go
  pkg/trace/sofa/rpc/types.go
Labels: cla:yes, size/S

#845 support arm
  pkg/utils/dup.go
  pkg/utils/dup_arm64.go
  pkg/utils/syscall.go
Labels: cla:yes, size/S

#828 fix dockerfile
  build/contrib/builder/image/Dockerfile
Labels: bug, cla:yes, size/S

#842 change address call
  pkg/filter/network/tcpproxy/proxy.go
  pkg/istio/control/http/report_data.go
  pkg/istio/mixerclient/client.go
  pkg/log/accesslog.go
  pkg/log/accesslog_test.go
  pkg/network/requestinfo.go
  pkg/proxy/upstream.go
  pkg/stream/http/connpool.go
  pkg/types/request.go
  pkg/types/upstream.go
Labels: size/M

#846 fix process time count
  pkg/proxy/downstream.go
Labels: bug, size/S

#844 use jsonpb for sds config json parse
  pkg/api/v2/types.go
  pkg/config/config_test.go
  pkg/config/data_test.go
  pkg/mtls/conn.go
  pkg/mtls/sds_tls_test.go
  pkg/mtls/secret_manager.go
  pkg/xds/conv/convertxds.go
Labels: size/L

#852 Remove docs folder and update some docs
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
  README.md
  README_CN.md
  README_EN.md
  docs/Catalog.md
  docs/Introduction.md
  docs/design/resource/DataFlowOpen.png
  docs/design/resource/MOSNMigration.png
  docs/design/resource/MOSNNetFlow2.png
  docs/design/resource/MOSNThreadModelStage1.png
  docs/design/resource/MOSNThreadModelStage2.png
  docs/design/resource/MosnDataFlow.png
  docs/design/resource/MosnGoroutineModel.png
  docs/design/resource/MosnModules.png
  docs/design/resource/MosnNetPoll.png
  docs/design/resource/MosnWorkFlow.png
  docs/design/resource/NetIO.png
  docs/design/resource/OriginModel.png
  docs/design/resource/stream.png
  docs/design/resource/subsetlb.png
  docs/develop/CONTRIBUTING.md
  docs/features/0.2.0/FrameworkExtend.md
  docs/features/0.2.0/FunctionAdded.md
  docs/features/0.2.0/GCOptimization.md
  docs/features/0.2.0/IOOptimization.md
  docs/features/0.2.0/README.md
  docs/features/0.2.0/TLSExtension.md
  docs/features/0.2.0/Xprotocol.md
  docs/images/MOSNIntroduction.png
  docs/images/bookinfo.png
  docs/images/login.png
  docs/images/v1.png
  docs/images/v2.png
  docs/images/v3.png
  docs/quickstart/RunSamples.md
  docs/quickstart/RunWithSOFAMesh.md
  docs/quickstart/Setup.md
  docs/reference/AccessLogDetails.md
  docs/reference/PerformanceReport010.md
  docs/reference/PerformanceReport021.md
Labels: cla:yes, size/XXL
