Repository mosn/mosn, pull requests merged in 2019-11, with the labels that each got.

#850 version upgrade 0.8.0
  VERSION
  docs/CHANGELOG.md
Labels: cla:yes, size/M

#854 Fix changelog
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
  README.md
  README_CN.md
  README_EN.md
  build/contrib/builder/image/Dockerfile
  docs/Catalog.md
  docs/Introduction.md
  docs/design/resource/DataFlowOpen.png
  docs/design/resource/MOSNMigration.png
  docs/design/resource/MOSNNetFlow2.png
  docs/design/resource/MOSNThreadModelStage1.png
  docs/design/resource/MOSNThreadModelStage2.png
  docs/design/resource/MosnDataFlow.png
  docs/design/resource/MosnGoroutineModel.png
  docs/design/resource/MosnModules.png
  docs/design/resource/MosnNetPoll.png
  docs/design/resource/MosnWorkFlow.png
  docs/design/resource/NetIO.png
  docs/design/resource/OriginModel.png
  docs/design/resource/stream.png
  docs/design/resource/subsetlb.png
  docs/develop/CONTRIBUTING.md
  docs/features/0.2.0/FrameworkExtend.md
  docs/features/0.2.0/FunctionAdded.md
  docs/features/0.2.0/GCOptimization.md
  docs/features/0.2.0/IOOptimization.md
  docs/features/0.2.0/README.md
  docs/features/0.2.0/TLSExtension.md
  docs/features/0.2.0/Xprotocol.md
  docs/images/MOSNIntroduction.png
  docs/images/bookinfo.png
  docs/images/login.png
  docs/images/v1.png
  docs/images/v2.png
  docs/images/v3.png
  docs/quickstart/RunSamples.md
  docs/quickstart/RunWithSOFAMesh.md
  docs/quickstart/Setup.md
  docs/reference/AccessLogDetails.md
  docs/reference/PerformanceReport010.md
  docs/reference/PerformanceReport021.md
Labels: bug, cla:yes, size/XXL

#855 doc: update SOFAMosn introductions
  README.md
  README_EN.md
Labels: cla:yes, size/S

#858 Update changelog
  CHANGELOG.md
  CHANGELOG_EN.md
  README.md
  README_EN.md
Labels: cla:yes, size/XL

#860 fix spell
  CHANGELOG_EN.md
  README.md
  README_EN.md
Labels: bug, cla:yes, size/XS

#857 tcpproxy example compile error Fixes gh-856
  examples/codes/tcpproxy-sample/rpc_client.go
Labels: First-time contributor, cla:yes, size/XS

#864 fix init logger not roller log
  pkg/log/logger.go
Labels: bug, cla:yes, size/S

#867 fix tracelog timeformat
  CHANGELOG.md
  CHANGELOG_EN.md
  README.md
  README_EN.md
  examples/codes/tcpproxy-sample/rpc_client.go
  pkg/trace/sofa/rpc/span.go
Labels: bug, cla:yes, size/XL

#861 add metrics: request failed
  pkg/metrics/downstream.go
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
  pkg/proxy/stats.go
  pkg/trace/sofa/rpc/tracer.go
Labels: cla:yes, size/M

#869 Adjust log
  pkg/mtls/sds/subscriber.go
  pkg/network/connection.go
  pkg/proxy/downstream.go
  pkg/router/routers_impl.go
  pkg/router/routers_manager.go
  pkg/types/log.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/healthcheck/tcpdial.go
  pkg/xds/conv/convertxds.go
  pkg/xds/conv/update.go
  pkg/xds/v2/adssubscriber.go
  pkg/xds/v2/xdsconfig.go
Labels: cla:yes, size/L

#871 lock mmap data to avoid I/O page fault, it might improve the performa…
  pkg/shm/shm.go
Labels: cla:yes, size/XS

#872 proxy work pool size to 256
  pkg/proxy/proxy.go
Labels: cla:yes, size/XS

#873 version 0.8.1
  CHANGELOG.md
  CHANGELOG_EN.md
  VERSION
Labels: cla:yes, size/M

#874 Stable
  CHANGELOG.md
  CHANGELOG_EN.md
  VERSION
  pkg/log/logger.go
  pkg/metrics/downstream.go
  pkg/mtls/sds/subscriber.go
  pkg/network/connection.go
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
  pkg/proxy/proxy.go
  pkg/proxy/stats.go
  pkg/router/routers_impl.go
  pkg/router/routers_manager.go
  pkg/shm/shm.go
  pkg/stream/http/stream.go
  pkg/trace/sofa/rpc/span.go
  pkg/trace/sofa/rpc/tracer.go
  pkg/types/log.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/healthcheck/tcpdial.go
  pkg/xds/conv/convertxds.go
  pkg/xds/conv/update.go
  pkg/xds/v2/adssubscriber.go
  pkg/xds/v2/xdsconfig.go
Labels: cla:yes, size/L

#811 fix http2 curClientStreams overflow
  pkg/module/http2/mhttp2.go
Labels: First-time contributor, bug, cla:yes, size/S

#879 Rename SOFAMosn to MOSN
  CHANGELOG.md
  CHANGELOG_EN.md
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
  README.md
  README_EN.md
Labels: cla:yes, size/M

#886 check buf is nil
  pkg/network/connection.go
Labels: First-time contributor, cla:yes, size/XS
