Repository mosn/mosn, pull requests merged in 2019-09, with the labels that each got.

#799 add target app index for remote
  pkg/trace/sofa/rpc/types.go
Labels: cla:yes, size/XS

#795 Fix xprotocol context issue
  pkg/stream/xprotocol/connpool.go
  pkg/stream/xprotocol/stream.go
Labels: bug, cla:yes, size/M

#801 Reduce the default size
  pkg/log/logger.go
  pkg/network/connection.go
  pkg/network/filtermanager.go
  pkg/stream/sofarpc/stream.go
Labels: cla:yes, size/S

#802 fix transfer error when inspector and TLS is on, but the conn is Plaintext
  pkg/network/transfer.go
  pkg/server/handler.go
  test/integrate/transfer/transfer_test.go
  test/util/config.go
Labels: bug, cla:yes, question, size/S

#804 admin api support help message
  pkg/admin/server/apis.go
  pkg/admin/server/server.go
  pkg/admin/server/server_test.go
Labels: cla:yes, size/M

#807 fix json file read in config
  pkg/api/v2/types.go
  pkg/config/config.go
  pkg/utils/file.go
  pkg/utils/file_test.go
Labels: bug, cla:yes, size/M

#809 fix errorlog fatal func
  pkg/log/errorlog.go
  pkg/log/logger.go
Labels: bug, cla:yes, size/S

#808 Temporary modification, heartbeat not counted for metric
  pkg/proxy/downstream.go
Labels: cla:yes, size/S

#810 fix roller init
  pkg/log/logger.go
  pkg/log/roller.go
  pkg/log/roller_test.go
Labels: bug, cla:yes, size/M

#812 fix read json bug and reconnect time
  pkg/api/v2/json_test.go
  pkg/api/v2/types.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/xds/v2/adssubscriber.go
Labels: bug, cla:yes, size/M

#813 Fix/healthcheck nodelay
  pkg/server/adapter.go
  pkg/upstream/healthcheck/healthchecker_test.go
  pkg/upstream/healthcheck/session_checker.go
  pkg/xds/v2/adssubscriber.go
Labels: bug, cla:yes, size/M

#814 update config dump with new cluster config
  pkg/upstream/cluster/cluster_manager.go
Labels: cla:yes, size/S

#815 fix read maybe causes dead loop
  pkg/buffer/iobuffer.go
  pkg/buffer/iobuffer_test.go
  pkg/network/connection.go
  pkg/network/connection_test.go
Labels: bug, cla:yes, size/M

#816 add log
  pkg/network/connection.go
Labels: cla:yes, size/XS

#817 fix read dead loop
  pkg/network/connection.go
  pkg/network/connection_test.go
Labels: bug, cla:yes, size/S

#819 Fix shm free concurrent problem
  pkg/metrics/shm/zone.go
  pkg/stream/http/stream.go
Labels: bug, cla:yes, size/L

#821 only increase client count when connection is successfully established.
  pkg/stream/http/connpool.go
Labels: cla:yes, question, size/XS

#822 modify log level
  pkg/network/connection.go
  pkg/proxy/downstream.go
  pkg/proxy/upstream.go
  pkg/sync/workerpool.go
Labels: cla:yes, size/M

#823 close internalStopChan and writeBufferChan anyway.
  pkg/network/connection.go
Labels: cla:yes, size/S

#825 Fix/upstream source
  pkg/stream/http/connpool.go
  pkg/upstream/cluster/mock_test.go
  pkg/upstream/cluster/resource_manager.go
Labels: bug, cla:yes, size/XL

#829 add codec error log
  pkg/stream/sofarpc/stream.go
Labels: cla:yes, size/S

#830 xds start in goroutine
  pkg/mosn/starter.go
Labels: cla:yes, size/XS
