Repository mosn/mosn, pull requests merged in 2020-11, with the labels that each got.

#1425 Feature istio adapter log format
  pkg/log/accesslog.go
  pkg/log/accesslog_test.go
  pkg/network/requestinfo.go
  pkg/proxy/var.go
  pkg/types/variable.go
Labels: area/istio

#1464 Update tracer.go
  pkg/trace/skywalking/http/tracer.go
Labels: kind/bug

#1452 several bugfixs
  pkg/filter/network/streamproxy/streamproxy.go
  pkg/proxy/var.go
  pkg/xds/conv/convertxds.go
  pkg/xds/conv/update_test.go
Labels: kind/bug

#1460 general streamFilter framework
  pkg/configmanager/parser.go
  pkg/configmanager/parser_test.go
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_downstream_test.go
  pkg/proxy/proxy_test.go
  pkg/proxy/streamfilters.go
  pkg/proxy/streamfilters_test.go
  pkg/server/handler.go
  pkg/streamfilter/chain.go
  pkg/streamfilter/chain_test.go
  pkg/streamfilter/config.go
  pkg/streamfilter/config_test.go
  pkg/streamfilter/factory.go
  pkg/streamfilter/factory_test.go
  pkg/streamfilter/manager.go
  pkg/streamfilter/manager_test.go
  pkg/streamfilter/mock_factory.go
  pkg/streamfilter/mock_manager.go
  pkg/types/context.go
Labels: area/filter, kind/enhancement

#1463 Bug Fix: nil pointer ref
  pkg/filter/stream/mixer/mixer.go
  pkg/istio/control/http/request_handler.go
Labels: kind/bug

#1451 Bugfix HTTP2: the `Content-length` may not be set correctly when direct response.
  pkg/proxy/downstream.go
  pkg/proxy/var.go
  pkg/stream/http2/stream.go
  pkg/stream/http2/stream_test.go
  pkg/types/proxy.go
  pkg/types/variable.go
Labels: kind/bug

#1493 fix bug 'getAPISourceEndpoint' when initializing adsclient
  pkg/xds/v2/xdsconfig.go
Labels: kind/bug
