Repository mosn/mosn, pull requests merged in 2021-01, with the labels that each got.

#1538 tls read buffer optimization
  pkg/mtls/conn.go
  pkg/mtls/crypto/tls/tls_custom.go
  test/util/xprotocol_rpc.go
Labels: WIP

#1558 fix x-mosn-path bug
  pkg/stream/http/stream.go
  pkg/stream/http2/stream.go
  test/cases/simple/http1_test.go
Labels: kind/bug

#1508 VirtualHost support perFilterConfig
  go.mod
  go.sum
  pkg/cel/extract/attributes_builder_test.go
  pkg/config/v2/route.go
  pkg/mock/api_route.go
  pkg/mock/mosn_route.go
  pkg/router/base_rule.go
  pkg/router/configutility.go
  pkg/router/http_rule.go
  pkg/router/routers_impl.go
  pkg/router/rpc_rule.go
  pkg/router/rpc_rule_test.go
  pkg/router/types.go
  pkg/router/variable_rule.go
  pkg/router/virtualhost.go
  pkg/types/alias.go
  pkg/types/route.go
  pkg/xds/conv/convertxds.go
  test/integrate/filter/perfilterconfig_test.go
  vendor/modules.txt
  vendor/mosn.io/api/route.go
Labels: kind/feature
