Repository mosn/mosn, pull requests merged in 2021-11, with the labels that each got.

#1823 chore: fix grammar in the admin server's help output.
  pkg/admin/server/apis.go
  pkg/admin/server/server_test.go
Labels: cla:yes, bug, size/XS, First-time contributor

#1826 prefix_write not work with "/"
  pkg/router/base_rule.go
Labels: cla:yes, size/XS

#1820 Fix/mosn unlink reconfig
  pkg/server/reconfigure.go
Labels: cla:yes, bug, size/XS

#1807 Fix doretry
  pkg/proxy/downstream.go
Labels: cla:yes, bug, size/XS

#1819 Fix/inherit config bugs
  pkg/mosn/mosn.go
Labels: cla:yes, bug, size/XS

#1831 Fix/http2 upstream reset
  pkg/module/http2/mhttp2.go
  test/cases/simple/http2_test.go
Labels: cla:yes, bug, size/M

#1835 fix the cert_loader demo: implemented two newly added interface methods.
  examples/codes/mosn-extensions/plugin/cert_loader/mosn_ext.go
Labels: cla:yes, bug, size/S

#1834 support admin api extends auth functions
  pkg/admin/server/api_test.go
  pkg/admin/server/apis.go
  pkg/admin/server/dumpconfig_test.go
  pkg/admin/server/handler.go
  pkg/admin/server/handler_test.go
  pkg/admin/server/server.go
  pkg/admin/server/server_test.go
Labels: kind/enhancement, cla:yes, size/L

#1828 Avoid unable to get the real reason in close connection scenarios
  pkg/stream/http/stream.go
Labels: cla:yes, bug, size/XS

#1837 default max header size to 8KB
  pkg/stream/http/stream.go
Labels: cla:yes, size/XS

#1839 fix issue #1833
  pkg/server/handler.go
Labels: kind/bug, cla:yes, bug, size/S, First-time contributor

#1803 update mosn.io/pkg
  go.mod
  go.sum
  vendor/modules.txt
  vendor/mosn.io/pkg/buffer/bytebuffer_pool.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/context.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/default.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/exports.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/imports.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/interface.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/spec.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/types.go
  vendor/mosn.io/proxy-wasm-go-host/proxywasm/v2/utils.go
Labels: cla:yes, size/XXL

#1843 Fix/h2 panic err
  pkg/module/http2/mhttp2.go
Labels: cla:yes, bug, size/XS

#1844 Proto ext
  go.mod
  go.sum
  pkg/mosn/init.go
  pkg/protocol/xprotocol/factory.go
  vendor/modules.txt
  vendor/mosn.io/api/xprotocol.go
Labels: kind/enhancement, cla:yes, size/M

#1815 feat: support dynamic phase
  pkg/filter/stream/transcoder/config.go
  pkg/filter/stream/transcoder/factory.go
  pkg/filter/stream/transcoder/factory_test.go
Labels: kind/enhancement, cla:yes, size/L

#1804 add some setter for pkg/mtls/crypto/tls.Conn
  pkg/mtls/crypto/README
  pkg/mtls/crypto/tls/tls_custom.go
  pkg/mtls/crypto/tls/tls_test.go
Labels: cla:yes, size/M

#1821 fix issue #1818
  pkg/stream/xprotocol/connpool_binding.go
Labels: cla:yes, bug, size/S, First-time contributor

#1845 bugfix: should close logger at the end, otherwise, may lost log during close Mosn instance, fix #1554.
  cmd/mosn/main/control.go
  istio/istio152/main/control.go
  pkg/mosn/stage_manager.go
  pkg/mosn/stage_manager_test.go
  pkg/server/server.go
Labels: cla:yes, bug, size/M

#1847 feature: added a after start stage in StageManager.
  pkg/mosn/stage_manager.go
  pkg/mosn/stage_manager_test.go
Labels: cla:yes, size/M

#1849 bugfix: codecClient is nil because has not been init
  pkg/stream/xprotocol/connpool_pingpong.go
Labels: kind/bug, cla:yes, size/XS, First-time contributor

#1853 fix: hc not work with unhealthyThreshold empty value
  pkg/upstream/healthcheck/healthchecker.go
Labels: cla:yes, bug, size/M

#1855 fix qr code
  README.md
  README_ZH.md
Labels: cla:yes, bug, size/XS

#1856 Admin API support Auth Extension and HTTP default header size set to 8K
  pkg/admin/server/api_test.go
  pkg/admin/server/apis.go
  pkg/admin/server/dumpconfig_test.go
  pkg/admin/server/handler.go
  pkg/admin/server/handler_test.go
  pkg/admin/server/server.go
  pkg/admin/server/server_test.go
  pkg/stream/http/stream.go
Labels: cla:yes, size/L

#1829 Feature: Support unix domain socket directory configuration
  pkg/config/v2/config.go
  pkg/mosn/default_stages.go
  pkg/mosn/init.go
  pkg/server/handler_test.go
  pkg/types/config.go
  pkg/types/config_test.go
Labels: kind/feature, cla:yes, size/M, First-time contributor

#1861 fix dead recursion #1860
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, bug, size/M
