Repository mosn/mosn, pull requests merged in 2021-12, with the labels that each got.

#1866 fix: chinese comma to english comma
  pkg/proxy/downstream.go
Labels: cla:yes, bug, size/XS

#1863 delete useless type assertion
  pkg/stream/xprotocol/conn.go
Labels: cla:yes, size/XS

#1868 Fix go.mod in wasm example codes
  examples/codes/wasm/sofarpc/go.mod
Labels: cla:yes, bug, size/XS, First-time contributor

#1870 feature: protocol match patch
  pkg/stream/http/stream.go
  test/integrate/protocol_auto_test.go
Labels: cla:yes, size/S

#1854 Refact/http conv
  cmd/mosn/main/mosn.go
  istio/istio152/main/mosn.go
  pkg/filter/stream/mirror/mirror.go
  pkg/filter/stream/transcoder/filter.go
  pkg/filter/stream/transcoder/http2bolt/http2bolt_simple.go
  pkg/filter/stream/transcoder/httpconv/http2_to_http.go
  pkg/filter/stream/transcoder/httpconv/http_to_http2.go
  pkg/protocol/conv.go
  pkg/protocol/conv_test.go
  pkg/protocol/http/conv/http1.go
  pkg/protocol/http2/conv/http2.go
  pkg/protocol/http2/types.go
  pkg/proxy/downstream.go
  pkg/proxy/streamfilters.go
  pkg/proxy/upstream.go
  test/cases/extends/tls_extend.go
  test/cases/retry/retry_test.go
  test/cases/streamfilter/transcoder/http_conv_test.go
  test/cases/tls/disable_test.go
  test/cases/tls/host_tls_test.go
  test/cases/tls/tls_extend_test.go
  test/cases/tls/tls_fallback_test.go
  test/integrate/common_test.go
  test/integrate/functiontest/http_test.go
  test/integrate/mirror_test.go
  test/integrate/retry_test.go
  test/integrate/tls_extend_test.go
  test/lib/extends/transcoder.go
  test/lib/http/client.go
  test/lib/http/config.go
  test/lib/http/http2.go
  test/lib/http/http2_test.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/modules.txt
Labels: cla:yes, size/XXL

#1871 fix: EDF wrr lb cannot choose a healthy host
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, bug, size/M

#1878 update README.md
  README.md
  README_ZH.md
Labels: cla:yes, size/XS

#1879 feat: modify trancoder
  pkg/filter/stream/transcoder/factory.go
  pkg/filter/stream/transcoder/factory_test.go
  pkg/filter/stream/transcoder/filter.go
  pkg/filter/stream/transcoder/http2bolt/http2bolt_simple.go
  pkg/filter/stream/transcoder/httpconv/http2_to_http.go
  pkg/filter/stream/transcoder/httpconv/http_to_http2.go
  pkg/filter/stream/transcoder/matcher/config.go
  pkg/filter/stream/transcoder/plugin.go
Labels: cla:yes, size/L

#1886 support set default http stream config
  pkg/stream/http/stream.go
  pkg/trace/sofa/span.go
Labels: cla:yes, size/S

#1893 bugfix: got the wrong CACert filename when converting the listen filter from istio, mosn may not listen success.
  go.mod
  go.sum
  istio/istio152/xds/conv/convertxds.go
  istio/istio152/xds/conv/convertxds_test.go
  vendor/github.com/andreyvit/diff/LICENSE
  vendor/github.com/andreyvit/diff/README.md
  vendor/github.com/andreyvit/diff/diff.go
  vendor/github.com/andreyvit/diff/doc.go
  vendor/github.com/andreyvit/diff/trim.go
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/operation_string.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/modules.txt
Labels: cla:yes, size/XXL, bug, question

#1894 fix STRICT_DNS_CLUSTER ResolveTarget cannot stop
  pkg/upstream/cluster/strict_dns_cluster.go
Labels: cla:yes, bug, size/XS

#1891 release v0.26.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/0.26.0.md
Labels: cla:yes, size/L

#1902 Fix-gh1900: invalid stream id err
  pkg/module/http2/mhttp2.go
  pkg/stream/http2/stream.go
Labels: cla:yes, bug, size/S
