Repository mosn/mosn, pull requests merged in 2021-07, with the labels that each got.

#1704 fix #1701
  pkg/mtls/crypto/cgosm3/sm3_cgo.go
  pkg/stream/xprotocol/conn.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
  test/cases/loadbalancer/subset_test.go
  test/lib/xprotocol/boltv1/config.go
  test/lib/xprotocol/boltv1/server.go
Labels: bug, cla:yes, size/L

#1707 fix: add OnConnectionEvent impl
  go.mod
  go.sum
  pkg/mock/network.go
  pkg/network/connection.go
  vendor/modules.txt
  vendor/mosn.io/api/network.go
Labels: bug, cla:yes, size/M

#1669 issue-1666: add route virtualhost support port match *
  pkg/router/routers_impl.go
  pkg/router/routers_impl_test.go
  pkg/router/types.go
Labels: cla:yes, kind/feature, size/L

#1722 WRRLB reuse RRLB
  pkg/upstream/cluster/loadbalancer.go
Labels: cla:yes, size/S

#1723 fix data race bug
  pkg/router/base_rule.go
Labels: bug, cla:yes, size/XS

#1716 Var interface value
  pkg/router/base_rule_test.go
  pkg/variable/api.go
  pkg/variable/api_test.go
  pkg/variable/deprecated.go
  pkg/variable/factory.go
  pkg/variable/protocolres.go
  pkg/variable/protocolres_test.go
  pkg/variable/types.go
  pkg/variable/var.go
Labels: cla:yes, kind/enhancement, size/L

#1726 Remove all deprecated variable API calls
  pkg/cel/ext/request.go
  pkg/cel/extract/attributes_builder.go
  pkg/cel/extract/attributes_builder_test.go
  pkg/filter/network/grpc/factory.go
  pkg/filter/network/grpc/var.go
  pkg/filter/stream/dsl/dsl_test.go
  pkg/filter/stream/dubbo/dubbo.go
  pkg/filter/stream/dubbo/var.go
  pkg/filter/stream/flowcontrol/callbacks.go
  pkg/filter/stream/flowcontrol/callbacks_test.go
  pkg/filter/stream/flowcontrol/stream_filter_test.go
  pkg/filter/stream/gzip/gzip.go
  pkg/filter/stream/gzip/gzip_test.go
  pkg/filter/stream/jwtauthn/filter.go
  pkg/filter/stream/jwtauthn/filter_test.go
  pkg/log/accesslog.go
  pkg/log/accesslog_test.go
  pkg/protocol/http/conv/http1.go
  pkg/protocol/http2/conv/http2.go
  pkg/protocol/mapping.go
  pkg/protocol/mapping_test.go
  pkg/protocol/types.go
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
  pkg/proxy/proxy_downstream_test.go
  pkg/proxy/retrystate_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
  pkg/proxy/var.go
  pkg/router/base_rule.go
  pkg/router/base_rule_test.go
  pkg/router/benchmark_test.go
  pkg/router/configutility.go
  pkg/router/configutility_test.go
  pkg/router/dsl_rule_test.go
  pkg/router/http_rule.go
  pkg/router/http_rule_test.go
  pkg/router/routers_impl.go
  pkg/router/routers_impl_test.go
  pkg/router/routers_manager_test.go
  pkg/router/var.go
  pkg/router/variable_rule.go
  pkg/router/variable_rule_test.go
  pkg/router/virtualhost_test.go
  pkg/stream/http/stream.go
  pkg/stream/http/stream_test.go
  pkg/stream/http/var.go
  pkg/stream/http/var_test.go
  pkg/stream/http2/stream.go
  pkg/stream/http2/stream_test.go
  pkg/stream/http2/var.go
  pkg/stream/http2/var_test.go
  pkg/stream/xprotocol/conn.go
  pkg/stream/xprotocol/stream.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/variable/api_test.go
  pkg/variable/factory.go
  pkg/variable/protocolres.go
  pkg/variable/protocolres_test.go
  test/lib/http/config.go
Labels: cla:yes, size/XL

#1714 feat: header_to_metadata streamfilter
  cmd/mosn/main/mosn.go
  go.mod
  go.sum
  pkg/filter/stream/headertometadata/factory.go
  pkg/filter/stream/headertometadata/filter.go
  pkg/filter/stream/headertometadata/filter_test.go
  pkg/mock/api_route.go
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
  pkg/proxy/gomock_test.go
  pkg/router/base_rule.go
  pkg/router/base_rule_test.go
  pkg/router/configutility.go
  pkg/router/var.go
  pkg/types/variable.go
  pkg/upstream/cluster/mock_test.go
  pkg/variable/api_test.go
  vendor/modules.txt
  vendor/mosn.io/api/route.go
Labels: cla:yes, size/XL

#1713 fix bug for issue #1711
  pkg/upstream/cluster/loadbalancer.go
Labels: bug, cla:yes, size/S

#1733 remove proxy-wasm-go-sdk from go.mod introduced by examples
  examples/codes/wasm/http/go.mod
  examples/codes/wasm/httpCall/go.mod
  examples/codes/wasm/sofarpc/go.mod
  go.mod
  go.sum
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/LICENSE
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_alloc.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_configuration.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_l4.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_l7.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_lifecycle.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_queue.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_test_export.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_timers.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_version.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/abi_version_010.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/context.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_lifecycle.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_logging.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_metric.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_utils_go.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_utils_tinygo.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/hostcall_utls.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/rawhostcall/README.md
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/rawhostcall/rawhostcall.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/rawhostcall/rawhostcall_mock.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/serde.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types/errors.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types/types.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/vmstate.go
  vendor/github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/vmstate_test_export.go
  vendor/modules.txt
Labels: cla:yes, size/XXL

#1730 fix #1701 (#1704)
  pkg/stream/xprotocol/conn.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
  test/cases/loadbalancer/subset_test.go
  test/lib/xprotocol/boltv1/config.go
  test/lib/xprotocol/boltv1/server.go
Labels: bug, cla:yes, size/L
