Repository mosn/mosn, pull requests merged in 2021-06, with the labels that each got.

#1665 fix rrLB bug, issues1663
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: kind/bug

#1695 fix http connection close invaild
  pkg/stream/http/stream.go
Labels: bug, cla:yes, kind/bug, size/XS

#1699 Support graceful for uds
  pkg/network/transfer.go
  test/integrate/transfer/transfer_test.go
  test/util/genconfig.go
  test/util/xprotocol_rpc.go
Labels: cla:yes, size/M

#1697 fix up potential sm3 mem leak
  pkg/mtls/crypto/cgosm3/sm3_cgo.go
Labels: bug, cla:yes, size/XS

#1660 Bugfix some minor issues.
  pkg/admin/server/apis.go
  pkg/mosn/mosn.go
Labels: cla:yes

#1673 fix #1672
  pkg/stream/http2/stream.go
Labels: bug, cla:yes

#1657 graceful SetHealthCheckerHostSet issue #1656
  pkg/upstream/healthcheck/healthchecker.go
  pkg/upstream/healthcheck/healthchecker_test.go
Labels: cla:yes, kind/enhancement, size/L
