Repository mosn/mosn, pull requests merged in 2021-09, with the labels that each got.

#1766 升级 gin 版本，并更新 seata filter demo readme 文件
  examples/cn_readme/seata/README.md
  examples/codes/seata/go.mod
  examples/codes/seata/server_a/service_a_config.json
  pkg/filter/stream/seata/filter.go
Labels: cla:yes

#1769 fix boltv2 heartbeat and trace
  pkg/protocol/xprotocol/boltv2/command.go
  pkg/protocol/xprotocol/boltv2/protocol.go
  pkg/protocol/xprotocol/boltv2/types.go
  pkg/trace/sofa/xprotocol/bolt/boltv2.go
Labels: cla:yes, size/L

#1764 fix typo, dubbo protocol error
  pkg/protocol/xprotocol/dubbo/protocol.go
  pkg/protocol/xprotocol/dubbo/types.go
Labels: cla:yes, bug, size/M

#1756 Feature/optimize h2 use stream
  etc/script/report.sh
  pkg/proxy/retrystate.go
  pkg/proxy/var.go
  pkg/stream/http2/stream.go
  pkg/stream/http2/stream_test.go
  pkg/stream/http2/var.go
  pkg/types/variable.go
  test/cases/simple/http2_test.go
Labels: cla:yes, size/XL, First-time contributor

#1757 Fixes gh-1751: catch h2 connection termination event
  pkg/module/http2/mhttp2.go
  pkg/stream/http2/connpool.go
  pkg/stream/http2/stream.go
Labels: cla:yes, size/M, First-time contributor

#1778 Remove the limit on the number of cpu cores when setting the gomaxproc via env.
  pkg/configmanager/parser.go
Labels: cla:yes, size/XS, question

#1782 Add metric for develop branch
  cmd/mosn/main/mosn.go
  pkg/config/v2/filter.go
  pkg/filter/network/grpc/factory.go
  pkg/filter/network/grpc/var.go
  pkg/filter/stream/grpcmetric/metric.go
  pkg/filter/stream/grpcmetric/metric_test.go
  pkg/filter/stream/grpcmetric/stats.go
Labels: cla:yes, size/L

#1783 [typo] typo fix in comment and param
  istio/istio152/xds/ads_config.go
  pkg/cel/extract/attributes_builder.go
  pkg/istio/attribute_names.go
  pkg/log/accesslog.go
  pkg/network/connection.go
  pkg/plugin/admin.go
  pkg/router/base_rule_test.go
  pkg/types/alias.go
Labels: cla:yes, bug, size/M, First-time contributor

#1789 Bugfix request info
  pkg/network/requestinfo.go
Labels: cla:yes, size/XS

#1788 fix xds action
  istio/istio152/xds/conv/convertxds.go
  pkg/mosn/default_stages.go
  pkg/mosn/mosn.go
Labels: kind/bug, cla:yes, bug, size/S

#1785 fix typo
  pkg/filter/network/grpc/conn.go
Labels: cla:yes, bug, cla:no, size/XS, First-time contributor

#1787 fix: add DNS-related fields when converting xds cluster config to v2 …
  istio/istio152/xds/conv/convertxds.go
Labels: cla:yes, bug, size/S, question

#1786 bugfix: recalculate frame length #1784
  pkg/protocol/xprotocol/bolt/encoder.go
  pkg/protocol/xprotocol/boltv2/encoder.go
Labels: cla:yes, size/M, First-time contributor

#1792 fix sds bug for xds refactory
  istio/istio152/sds/sds.go
  istio/istio152/sds/sds_test.go
  pkg/config/v2/tls.go
Labels: cla:yes, bug, size/L

#1794 reduce memory alloc on create subset loadbalancer
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: area/performance, cla:yes, size/M, First-time contributor

#1779 feat: AddOrUpdate/Get API for listener/network filter factories
  pkg/configmanager/parser.go
  pkg/configmanager/parser_test.go
  pkg/network/connection.go
  pkg/network/filtermanager.go
  pkg/network/filtermanager_test.go
  pkg/proxy/proxy.go
  pkg/server/handler.go
Labels: cla:yes, size/L

#1767 add metric for grpc
  pkg/filter/network/grpc/factory.go
  pkg/filter/network/grpc/var.go
  pkg/filter/stream/grpcmetric/metric.go
  pkg/filter/stream/grpcmetric/metric_test.go
Labels: cla:yes, size/M

#1772 Bugfix some issue when close connection
  pkg/proxy/downstream.go
  pkg/stream/http/stream.go
Labels: cla:yes, size/S

#1780 fix: 服务宕机的情况，收不到 response，无法对状态码进行判断，默认业务请求执行失败。
  examples/codes/seata/go.mod
  examples/codes/seata/go.sum
  pkg/filter/stream/seata/branch_transaction_service.go
  pkg/filter/stream/seata/filter.go
Labels: cla:yes, bug, size/M

#1781 optimize grpc server
  pkg/filter/network/grpc/factory.go
  pkg/filter/network/grpc/filter.go
  pkg/filter/network/grpc/filter_test.go
  pkg/filter/network/grpc/grpc_test.go
  pkg/filter/network/grpc/listener.go
Labels: cla:yes, size/L
