Repository mosn/mosn, pull requests merged in 2021-08, with the labels that each got.

#1732 fix: subsetLoadBalancer.HostNum do not consider fallback policy
  pkg/upstream/cluster/cluster_adapter_test.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: bug, cla:yes, size/M

#1731 enhance grpc networkFilter graceful stop
  pkg/config/v2/grpc.go
  pkg/filter/network/grpc/factory.go
  pkg/network/listener.go
  pkg/server/handler.go
Labels: cla:yes, size/M

#1737 release v0.24.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/0.24.0.md
Labels: cla:yes, size/XL

#1739 Feature request header remove.
  pkg/config/v2/json_test.go
  pkg/config/v2/route.go
  pkg/router/base_rule.go
  pkg/router/base_rule_test.go
  pkg/router/configutility.go
  pkg/router/configutility_test.go
  pkg/router/virtualhost.go
  pkg/xds/conv/convertxds.go
Labels: cla:yes, size/S

#1740 [IMP]use -mod vendor instead GO111MODULE=off
  Makefile
Labels: cla:yes, cla:no

#1741 feat: wasm manager support reload
  pkg/config/v2/wasm.go
  pkg/wasm/manager.go
  pkg/wasm/manager_test.go
  pkg/wasm/plugin.go
Labels: cla:yes, size/M, First-time contributor

#1752 Fixes gh-1750: retry hangs if empty hosts.
  pkg/proxy/downstream.go
  pkg/proxy/downstream_test.go
Labels: cla:yes, cla:no, size/M

#1749 修复 msgconnpool
  pkg/stream/connpool/msgconnpool/activeclient.go
  pkg/trace/api.go
Labels: kind/bug, cla:yes, size/M

#1736 enhance edf LB, pick random times
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, size/S

#1761 opt edf performance
  pkg/upstream/cluster/edf.go
  pkg/upstream/cluster/edf_test.go
Labels: kind/enhancement, area/loadbalancer
