Repository mosn/mosn, pull requests merged in 2022-06, with the labels that each got.

#2014 Feature/zipkin support
  cmd/mosn/main/control.go
  examples/codes/trace/zipkin/http/client.go
  examples/codes/trace/zipkin/http/mosn_config.yaml
  examples/codes/trace/zipkin/http/server.go
  go.mod
  go.sum
  istio/_istio152/main/control.go
  istio/istio1106/main/control.go
  pkg/trace/zipkin/config.go
  pkg/trace/zipkin/driver.go
  pkg/trace/zipkin/noop_span.go
  pkg/trace/zipkin/progagation.go
  pkg/trace/zipkin/reporter_factory.go
  pkg/trace/zipkin/span.go
  pkg/trace/zipkin/tracer.go
  pkg/trace/zipkin/types.go
Labels: cla:yes, size/XL

#1640 feat: support tunnel conn
  cmd/mosn/main/mosn.go
  examples/codes/tunnel-sample/agent_config.json
  examples/codes/tunnel-sample/build.sh
  examples/codes/tunnel-sample/client.go
  examples/codes/tunnel-sample/client_config.json
  examples/codes/tunnel-sample/credential.go
  examples/codes/tunnel-sample/server.go
  pkg/config/v2/filter.go
  pkg/filter/network/tunnel/agent.go
  pkg/filter/network/tunnel/backend_connection.go
  pkg/filter/network/tunnel/connection.go
  pkg/filter/network/tunnel/connection_test.go
  pkg/filter/network/tunnel/ext/base.go
  pkg/filter/network/tunnel/factory.go
  pkg/filter/network/tunnel/filter.go
  pkg/filter/network/tunnel/host.go
  pkg/filter/network/tunnel/host_remover.go
  pkg/filter/network/tunnel/protocol.go
  pkg/filter/network/tunnel/protocol_test.go
  pkg/mock/upstream.go
  pkg/mosn/mosn.go
  pkg/network/connection.go
  pkg/network/idlechecker_test.go
  pkg/network/listener.go
  pkg/network/listener_test.go
  pkg/network/transfer.go
  pkg/network/udpreceiver.go
  pkg/server/handler.go
  pkg/stream/connpool/msgconnpool/connpool.go
  pkg/types/context.go
  pkg/types/network.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster_manager.go
  test/integrate/tunnel/credential_test.go
  test/integrate/tunnel/tunnel_test.go
  test/util/xprotocol_rpc.go
Labels: kind/feature, cla:yes, size/XXL

#2051 引用的buffer.ConnReadTimeout 变更为 types.DefaultConnReadTimeout
  pkg/network/connection.go
  pkg/network/idlechecker.go
  pkg/network/idlechecker_test.go
  pkg/network/transfer.go
  pkg/server/adapter_test.go
  pkg/server/handler.go
  pkg/server/server.go
  pkg/stream/connpool/msgconnpool/connpool_test.go
  pkg/stream/xprotocol/idlefree.go
  pkg/types/network.go
  pkg/upstream/cluster/host.go
  pkg/upstream/cluster/host_test.go
Labels: cla:yes, size/L

#2048 enhance cluster update hosts
  Makefile
  istio/istio1106/main/control.go
  pkg/config/v2/upstream.go
  pkg/filter/network/tunnel/filter.go
  pkg/mock/upstream.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/cluster_adapter.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/cluster/cluster_manager_test.go
  pkg/upstream/cluster/cluster_test.go
  pkg/upstream/cluster/strict_dns_cluster.go
Labels: cla:yes, size/XXL

#2053 optimize certificate matching logic
  pkg/mtls/tls_context_manager.go
  pkg/mtls/tls_context_manager_test.go
Labels: cla:yes, size/M

#2049 feat:#1810
  pkg/log/proxylog.go
  pkg/log/proxylog_test.go
  pkg/stream/http/connpool.go
  pkg/stream/http2/connpool.go
  pkg/stream/xprotocol/connpool_binding.go
  pkg/stream/xprotocol/connpool_multiplex.go
  pkg/stream/xprotocol/connpool_pingpong.go
  pkg/types/context.go
  pkg/types/variable.go
Labels: kind/enhancement, cla:yes, size/M

#2036 hostSet method && export NewClusterInfo
  istio/_istio152/istio/mixerclient/client.go
  istio/istio1106/istio/mixerclient/client.go
  pkg/filter/network/tunnel/filter.go
  pkg/filter/stream/mirror/mirror.go
  pkg/mock/upstream.go
  pkg/types/upstream.go
  pkg/upstream/cluster/benchmark_test.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/cluster_adapter_test.go
  pkg/upstream/cluster/cluster_healthcheck_test.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/cluster/cluster_test.go
  pkg/upstream/cluster/host_set.go
  pkg/upstream/cluster/host_set_test.go
  pkg/upstream/cluster/lb_register_test.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
  pkg/upstream/cluster/mock_test.go
  pkg/upstream/cluster/strict_dns_cluster.go
  pkg/upstream/cluster/strict_dns_cluster_test.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_builder.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
  pkg/upstream/healthcheck/healthchecker.go
  pkg/upstream/healthcheck/healthchecker_test.go
  pkg/upstream/healthcheck/mock_test.go
Labels: cla:yes, size/XL

#2056 fix typo
  cmd/mosn/main/control.go
Labels: cla:yes

#2058 bugfix: restore return line
  pkg/server/handler.go
Labels: cla:yes, size/XS

#2059 add subset lb interface
  pkg/types/loadbalancer.go
  pkg/upstream/cluster/cluster_test.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: cla:yes, size/M
