Repository mosn/mosn, pull requests merged in 2022-04, with the labels that each got.

#1979 improvement: added more suggestions for how to contribute.
  CONTRIBUTING_ZH.md
Labels: cla:yes, size/M, question

#1996 fix some log action
  cmd/mosn/main/control.go
  go.mod
  go.sum
  istio/_istio152/main/control.go
  istio/istio1106/main/control.go
  pkg/router/virtualhost.go
  vendor/modules.txt
  vendor/mosn.io/pkg/buffer/iobuffer_pool.go
  vendor/mosn.io/pkg/buffer/log.go
  vendor/mosn.io/pkg/log/logger.go
Labels: cla:yes, bug, size/L

#1998 release version 0.27.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/0.27.0.md
Labels: cla:yes, size/L

#2000 example: changed to use the new config style for downstream_protocol & upstream_protocol.
  examples/codes/dubbo/client_config.json
  examples/codes/dubbo/server_config.json
  examples/codes/filter/dubbo/install/build/mosn_config_dubbo_xds.json
  examples/codes/filter/transcoder/server_config.json
  examples/codes/http-sample/client_config.json
  examples/codes/sofarpc-with-xprotocol-sample/client_config.json
  examples/codes/sofarpc-with-xprotocol-sample/server_config.json
  examples/codes/sofarpc-with-xprotocol-sample/tls_client_config.json
  examples/codes/sofarpc-with-xprotocol-sample/tls_server_config.json
Labels: cla:yes, size/M

#2001 fix: update all hosts in strict dns cluster mode(#1994).
  pkg/upstream/cluster/strict_dns_cluster.go
  pkg/upstream/cluster/strict_dns_cluster_test.go
Labels: cla:yes, bug, size/M

#1999 Feature: support more configuration for l7 health check
  pkg/upstream/healthcheck/httpdial.go
  pkg/upstream/healthcheck/httpdial_test.go
Labels: cla:yes, size/L

#1992 fix: extension config not split (#1991)
  pkg/filter/network/proxy/factory.go
  pkg/proxy/proxy_test.go
  pkg/stream/http/stream.go
  pkg/stream/http/stream_test.go
  pkg/stream/http2/stream.go
  pkg/stream/http2/stream_test.go
Labels: cla:yes, bug, size/L

#2006 fix: align to the old exit code(2) when failed to inherit from old mosn.
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, bug, size/S, question

#2002 feat: Add version api for adminApi
  Makefile
  cmd/mosn/main/control.go
  examples/codes/filter/dubbo/install/Makefile
  istio/_istio152/main/control.go
  istio/istio1106/main/control.go
  pkg/admin/server/api_test.go
  pkg/admin/server/apis.go
  pkg/admin/server/server.go
Labels: cla:yes, size/M, First-time contributor

#2005 Add old http health check test cases back
  pkg/upstream/healthcheck/httpdial_test.go
Labels: cla:yes, size/M

#2011 fix init metrics and variable
  pkg/mosn/init.go
Labels: cla:yes, bug, size/XS

#2004 test: added a new shell mode to test the mosn command.
  .github/workflows/reviewdog.yml
  Makefile
  test/test-shell.sh
Labels: cla:yes, size/M

#1990 Mosn stop command
  cmd/mosn/main/control.go
  istio/_istio152/main/control.go
  istio/istio1106/main/control.go
  pkg/server/pid/pid.go
  pkg/stagemanager/stage_manager.go
  test/test-shell.sh
Labels: cla:yes, size/L

#2013 release v1.0.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  README.md
  README_ZH.md
  VERSION
Labels: cla:yes

#2016 fix:#2012
  pkg/upstream/cluster/strict_dns_cluster_test.go
Labels: cla:yes, bug, size/M

#2018 [Protocol] Bolt v1 v2 maps status code api.NoHealthUpstreamCode -> ResponseStatus…
  pkg/protocol/xprotocol/bolt/protocol.go
  pkg/protocol/xprotocol/bolt/protocol_test.go
  pkg/protocol/xprotocol/boltv2/protocol.go
  test/cases/loadbalancer/subset_test.go
  test/cases/streamfilter/terminate/terminate_test.go
  test/cases/tls/tls_fallback_test.go
Labels: cla:yes, size/S
