Repository mosn/mosn, pull requests merged in 2022-02, with the labels that each got.

#1945 change: sdsclient add new api: fetch and require cert, see details in…
  istio/istio152/sds/fake_sds_test.go
  istio/istio152/sds/sds.go
  istio/istio152/sds/sds_test.go
  pkg/mtls/mock_test.go
  pkg/mtls/sds/client.go
  pkg/mtls/sds/mock_test.go
  pkg/mtls/sds/subscriber.go
  pkg/types/tls.go
Labels: cla:yes, size/L

#1942 add InitialDelaySeconds healthChecker config and HTTPDial
  pkg/config/v2/upstream.go
  pkg/upstream/healthcheck/healthchecker.go
  pkg/upstream/healthcheck/healthchecker_test.go
  pkg/upstream/healthcheck/httpdial.go
  pkg/upstream/healthcheck/httpdial_test.go
  pkg/upstream/healthcheck/session_checker.go
  test/cases/cluster/healthcheck/http_healthcheck_test.go
Labels: cla:yes, size/XL, First-time contributor

#1958 refactor: sds secret manager support a certificate to create different tls config
  istio/istio152/xds/conv/convertxds.go
  istio/istio152/xds/conv/convertxds_test.go
  pkg/config/v2/tls.go
  pkg/mtls/confighook_test.go
  pkg/mtls/mock_test.go
  pkg/mtls/provider.go
  pkg/mtls/sds_tls_test.go
  pkg/mtls/secret_manager.go
  pkg/mtls/static_tls_test.go
  pkg/mtls/tls_context.go
  pkg/mtls/tls_context_manager.go
  pkg/mtls/tls_context_test.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/cluster_manager.go
  test/util/xprotocol_rpc.go
Labels: cla:yes, size/XL

#1961 move import keeper from pkg/mosn to cmd/mosn/main
  cmd/mosn/main/mosn.go
  go.mod
  istio/istio152/main/control.go
  pkg/mosn/init.go
  test/util/mosn/mosn.go
  vendor/modules.txt
Labels: cla:yes, size/XS

#1963 fix missing errors for debug log format.
  pkg/upstream/cluster/strict_dns_cluster.go
Labels: cla:yes, bug, size/XS

#1964 style:maglev load balancer arrays pre-allocation
  pkg/upstream/cluster/loadbalancer.go
Labels: cla:yes, size/XS, First-time contributor

#1887 [Feature] Add TlsContext callback; Add server/clientConnFactory and listenerFactory
  go.mod
  go.sum
  pkg/mock/mtls_types.go
  pkg/mock/tls.go
  pkg/mock/tls_context.go
  pkg/mock/update.sh
  pkg/mtls/mock_test.go
  pkg/mtls/provider.go
  pkg/mtls/sds_tls_test.go
  pkg/mtls/secret_manager.go
  pkg/mtls/tls_context.go
  pkg/mtls/tls_context_test.go
  pkg/network/connection.go
  pkg/network/idlechecker_test.go
  pkg/network/listener.go
  pkg/network/listener_test.go
  pkg/server/handler.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: cla:yes, size/XXL
