Repository mosn/mosn, pull requests merged in 2022-08, with the labels that each got.

#2091 Revert "support xds for stream filter"
  go.mod
  go.sum
  istio/_istio152/xds/conv/convertxds.go
  istio/istio1106/xds/conv/convert_listener.go
  pkg/filter/stream/ipaccess/pb/ip_access.pb.go
  pkg/filter/stream/ipaccess/pb/ip_access.proto
  pkg/filter/stream/ipaccess/stream_filter_factory.go
Labels: cla:yes, size/L

#2080 bugfix: tcp proxy handle write timeout or write close event
  pkg/filter/network/streamproxy/streamproxy.go
Labels: cla:yes, size/M

#2093 bugfix: nil variable upstream_local_address replaced by '-'
  pkg/proxy/var.go
Labels: cla:yes, size/XS

#2095 support stream filter for xds
  go.mod
  go.sum
  istio/_istio152/xds/conv/convertxds.go
  istio/istio1106/xds/conv/convert_listener.go
  pkg/filter/stream/ipaccess/pb/ip_access.pb.go
  pkg/filter/stream/ipaccess/pb/ip_access.proto
  pkg/filter/stream/ipaccess/stream_filter_factory.go
Labels: cla:yes, size/L

#2075 add xds-server config sample
  examples/cn_readme/xds-server-sample/README.md
  examples/codes/xds-server-sample/Dockerfile
  examples/codes/xds-server-sample/Makefile
  examples/codes/xds-server-sample/apis/v1alpha1/envoy.go
  examples/codes/xds-server-sample/cmd/server/main.go
  examples/codes/xds-server-sample/cmd/upstream/main.go
  examples/codes/xds-server-sample/config.json
  examples/codes/xds-server-sample/config/config.yaml
  examples/codes/xds-server-sample/go.mod
  examples/codes/xds-server-sample/hack/bootstrap.yaml
  examples/codes/xds-server-sample/hack/start-envoy.sh
  examples/codes/xds-server-sample/internal/processor/parser.go
  examples/codes/xds-server-sample/internal/processor/processor.go
  examples/codes/xds-server-sample/internal/resources/cache.go
  examples/codes/xds-server-sample/internal/resources/resource.go
  examples/codes/xds-server-sample/internal/server/server.go
  examples/codes/xds-server-sample/internal/watcher/watcher.go
  examples/codes/xds-server-sample/internal/xdscache/cache.go
  examples/en_readme/xds-server-sample/README.md
Labels: cla:yes, size/XXL

#2098 [bugfix]: newActiveConnection before InitializeReadFilters to avoid close event coming before new connection
  pkg/server/handler.go
Labels: cla:yes, size/S

#2087 refactor: disable WriteLoop to reduce code complexity
  pkg/config/v2/server.go
  pkg/filter/network/grpc/factory.go
  pkg/mosn/mosn.go
  pkg/network/connection.go
Labels: cla:yes, size/M

#2085 optimize: reduce memory usage during http post requests
  pkg/stream/http/stream.go
Labels: cla:yes, size/S

#1968 chore: Makefile: added a section to build tar file for building istio sidecar image.
  .gitignore
  Makefile
  pkg/server/handler.go
Labels: cla:yes, size/S

#2035 feat: fix bugfix stream
  pkg/stream/http/stream.go
  pkg/stream/http2/stream.go
Labels: cla:yes, bug, size/XS

#2101 update istio1106 xds config update Concurrency issues
  istio/istio1106/xds/client.go
Labels: kind/bug, cla:yes, size/M, First-time contributor

#2024 feature: support envoy.lb for filter_metadata
  istio/istio1106/xds/conv/convert_router.go
Labels: cla:yes, size/XS, First-time contributor

#2077 maglev loadbalancer support skipping last chosen host when retrying
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: kind/enhancement, cla:yes, size/M, question

#2107 Support access log to print traceID and connectionID
  pkg/proxy/var.go
  pkg/types/accesslog.go
  pkg/types/variable.go
Labels: cla:yes, size/M

#2084 Hotfix/health check
  istio/istio1106/xds/conv/convert_cluster.go
  istio/istio1106/xds/conv/convert_cluster_test.go
Labels: cla:yes, size/M
