Repository mosn/mosn, pull requests merged in 2022-12, with the labels that each got.

#2191 release version v1.3.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/1.3.0.md
Labels: cla:yes, size/L

#2189 proxywasm: reduces logging in benchmarks
  test/integrate/proxywasm/proxywasm_test.go
Labels: cla:yes, size/XS

#2198 merge subset mem improve
  pkg/upstream/cluster/subset_loadbalancer_builder.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: cla:yes, size/M

#2096 [feature] support record health check log
  istio/istio1106/xds/conv/convert_cluster.go
  pkg/config/v2/upstream.go
  pkg/types/healthcheck.go
  pkg/upstream/healthcheck/healthchecker.go
  pkg/upstream/healthcheck/healthchecklog.go
  pkg/upstream/healthcheck/healthchecklog_test.go
  pkg/upstream/healthcheck/session_checker.go
Labels: cla:yes, size/L

#2184 [feature] add least_connection load balancer
  pkg/types/loadbalancer.go
  pkg/upstream/cluster/lb_leastconnection.go
  pkg/upstream/cluster/lb_leastconnection_test.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, size/L

#2183 Add api to force reconnect and send ads request
  pkg/istio/xds.go
  pkg/istio/xds_test.go
Labels: cla:yes, size/M

#2199 Optimize match route logic, try to update routerWrapper when it is nil
  istio/_istio152/xds/conv/update.go
Labels: cla:yes, size/XS, question

#2201 bugfix: enlarge udp dns resolve buffer
  go.mod
  go.sum
  pkg/network/dns.go
Labels: cla:yes, size/S

#2204 [bugfix] debug server support inherit fd
  pkg/mosn/mosn.go
Labels: cla:yes, size/XS

#2202 [Feature] pprof debug server support endpoint configure
  pkg/config/v2/config.go
  pkg/mosn/init.go
Labels: cla:yes, size/S

#2205 [bugfix]: if new Mosn starts from upgrade mode fails, do no unlink reconfig.sock
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, size/XS, question

#2207 [bugfix]http health check url with query string will be unescaped
  pkg/upstream/healthcheck/httpdial.go
  pkg/upstream/healthcheck/httpdial_test.go
Labels: cla:yes, size/M

#2209 [bugfix]: lb ReqRoundRobin fails to choose host when index exceeds hosts length
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, size/S, question
