Repository mosn/mosn, pull requests merged in 2022-01, with the labels that each got.

#1918 [fix]version number
  cmd/mosn/main/mosn.go
Labels: cla:yes, bug, size/XS

#1913 [fix]adjust the module name in the examples code
  examples/codes/seata/go.mod
  examples/codes/wasm/http/go.mod
  examples/codes/wasm/httpCall/go.mod
  examples/codes/wasm/sofarpc/go.mod
Labels: cla:yes, bug, size/XS

#1881 chore: removed the unused field in the connection struct.
  pkg/network/connection.go
Labels: cla:yes, size/XS

#1899 fix problems of xprotocol goplugin example
  examples/codes/xprotocol_with_goplugin_example/client_config.json
  examples/codes/xprotocol_with_goplugin_example/codec.go
  examples/codes/xprotocol_with_goplugin_example/codec/types.go
  examples/codes/xprotocol_with_goplugin_example/server_config.json
Labels: cla:yes, bug, size/S, First-time contributor

#1908 chore: added a direct response sample in the default mosn_config.json.
  configs/mosn_config.json
Labels: cla:yes, size/M

#1905 chore: used the "/var/run/" path instead of "/dev/shm/" path for supervisor in docker image.
  etc/supervisor/supervisord.conf
Labels: cla:yes, size/XS

#1859 refactor: make signal handler simpler
  cmd/mosn/main/control.go
  examples/codes/dubbo/client_config.json
  examples/codes/dubbo/server_config.json
  examples/codes/filter/ipaccess/config.json
  examples/codes/filter/jwtauthn/config.json
  examples/codes/filter/transcoder/client_config.json
  examples/codes/filter/transcoder/server_config.json
  examples/codes/flowcontrol-sample/client_config.json
  examples/codes/flowcontrol-sample/server_config.json
  examples/codes/flowcontrol-sample/tls_client_config.json
  examples/codes/flowcontrol-sample/tls_server_config.json
  examples/codes/http-sample/client_config.json
  examples/codes/http-sample/server_config.json
  examples/codes/http-sample/tls_client_config.json
  examples/codes/http-sample/tls_server_config.json
  examples/codes/protocol-auto-sample/client_config.json
  examples/codes/protocol-auto-sample/server_config.json
  examples/codes/protocol-auto-sample/tls_client_config.json
  examples/codes/protocol-auto-sample/tls_server_config.json
  examples/codes/seata/server_a/service_a_config.json
  examples/codes/seata/server_b/service_b_config.json
  examples/codes/seata/server_c/service_c_config.json
  examples/codes/sofarpc-with-xprotocol-sample/client_config.json
  examples/codes/sofarpc-with-xprotocol-sample/server_config.json
  examples/codes/sofarpc-with-xprotocol-sample/tls_client_config.json
  examples/codes/sofarpc-with-xprotocol-sample/tls_server_config.json
  examples/codes/uds-sample/client_config.json
  examples/codes/uds-sample/server_config.json
  examples/codes/xprotocol_with_goplugin_example/client_config.json
  examples/codes/xprotocol_with_goplugin_example/server_config.json
  istio/istio152/main/control.go
  istio/istio152/xds/admin.go
  istio/istio152/xds/admin_test.go
  pkg/admin/server/apis.go
  pkg/admin/server/server_test.go
  pkg/admin/store/state.go
  pkg/config/v2/config.go
  pkg/filter/network/grpc/factory.go
  pkg/mock/stm_app.go
  pkg/mosn/default_stages.go
  pkg/mosn/init.go
  pkg/mosn/mosn.go
  pkg/mosn/mosn_test.go
  pkg/mosn/stage_manager.go
  pkg/mosn/stage_manager_test.go
  pkg/network/transfer.go
  pkg/networkextention/init.go
  pkg/server/handler.go
  pkg/server/keeper/serverkeeper.go
  pkg/server/pid/pid.go
  pkg/server/reconfigure.go
  pkg/stagemanager/stage_manager.go
  pkg/stagemanager/stage_manager_test.go
  test/integrate/filter/perfilterconfig_test.go
  test/integrate/functiontest/faultinject_test.go
  test/integrate/functiontest/keepalive_test.go
  test/integrate/functiontest/redirect_test.go
  test/integrate/functiontest/update_streamfilter_test.go
  test/util/mosn/mosn.go
Labels: cla:yes, size/XXL

#1920 feat: edfSchduler can be faster by maintaining heap manually (#1919)
  go.mod
  pkg/upstream/cluster/edf.go
  pkg/upstream/cluster/edfheap.go
  pkg/upstream/cluster/edfheap_test.go
Labels: cla:yes, size/L, First-time contributor, question

#1923 [imp]set GO111MODULE=on in the Makefile by default
  Makefile
  build/contrib/builder/binary/Dockerfile
  etc/script/report.sh
  test/cases/run_all.sh
Labels: cla:yes, size/M

#1917 [imp]ignore target dir of dubbo example code
  .gitignore
  examples/codes/dubbo/.gitignore
Labels: cla:yes, size/XS

#1931 fix handle error in originalDst network filter
  pkg/filter/listener/originaldst/originaldst.go
Labels: cla:yes, bug

#1935 Bugfix networkextension build error.
  pkg/networkextention/Makefile
Labels: cla:yes, size/S

#1914 feature: add idletimeout into upstream cluster
  istio/istio152/xds/conv/convertxds.go
  istio/istio152/xds/conv/convertxds_test.go
  pkg/config/v2/upstream.go
  pkg/mock/upstream.go
  pkg/proxy/retrystate_test.go
  pkg/stream/http/connpool_test.go
  pkg/stream/xprotocol/mock_test.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/host.go
  pkg/upstream/cluster/host_test.go
Labels: cla:yes, size/XXL

#1936 change: log related use logbuffer instead of iobuffer
  go.mod
  go.sum
  pkg/log/accesslog.go
  pkg/log/types.go
  pkg/trace/sofa/span.go
  vendor/modules.txt
  vendor/mosn.io/pkg/buffer/iobuffer_pool.go
  vendor/mosn.io/pkg/log/buffer.go
  vendor/mosn.io/pkg/log/logger.go
  vendor/mosn.io/pkg/log/roller.go
Labels: cla:yes, size/L

#1949 fix: memery recycel in Http1 protocl
  pkg/stream/http/stream.go
Labels: cla:yes, bug, size/XS

#1946 feature: support manipulate headers with variables
  pkg/proxy/upstream.go
  pkg/proxy/var.go
  pkg/router/base_rule.go
  pkg/router/header_parser.go
  pkg/router/headerformatter.go
  pkg/router/headerformatter_test.go
  pkg/router/headerparser_test.go
  pkg/router/types.go
  pkg/router/virtualhost.go
Labels: cla:yes, size/L

#1927 fix: correct spelling errors in "Resgiter"
  istio/istio152/xds/parse_config.go
  pkg/istio/README_CN.md
  pkg/istio/factory.go
  pkg/istio/xds_test.go
  pkg/protocol/api.go
  pkg/protocol/internal/registry/registry.go
Labels: cla:yes, bug, size/S, First-time contributor

#1952 Fix: more detailed error hint for variable.Get
  pkg/variable/api_test.go
  pkg/variable/var.go
Labels: cla:yes, bug, size/S

#1924 chore: added the update.sh script to regenerate mock module in batch.
  pkg/mock/api_route.go
  pkg/mock/header.go
  pkg/mock/network.go
  pkg/mock/network_filter.go
  pkg/mock/readme.md
  pkg/mock/stream.go
  pkg/mock/stream_filter.go
  pkg/mock/trace.go
  pkg/mock/update.sh
  pkg/mock/wasm.go
Labels: cla:yes, size/XXL

#1956 Optimizes stream reset logical
  pkg/proxy/proxy.go
Labels: cla:yes, size/XS

#1883 fix: cannot start a stopped listener properly
  pkg/network/listener.go
Labels: cla:yes, bug, size/M
