Repository mosn/mosn, pull requests merged in 2022-11, with the labels that each got.

#2129 bugfix: smooth upgrade failed
  go.sum
  pkg/mock/stm_app.go
  pkg/mosn/mosn.go
  pkg/mosn/mosn_test.go
  pkg/stagemanager/stage_manager.go
  pkg/stagemanager/stage_manager_test.go
  test/util/mosn/mosn.go
Labels: kind/bug, cla:yes, size/M

#2160 Builds with Go 1.18, but tests with 1.17, 1.18 and 1.19
  .github/workflows/reviewdog.yml
  Makefile
  build/contrib/builder/wasm/Dockerfile
  examples/codes/wasm/sofarpc/go.sum
  examples/codes/xds-server-sample/go.sum
  go.mod
  go.sum
  pkg/module/http2/server_test.go
Labels: cla:yes, size/XL, First-time contributor

#2164 Adds integrated benchmarks for proxywasm
  test/integrate/proxywasm/proxywasm_test.go
  test/integrate/proxywasm/testdata/req-header-v1/go.mod
  test/integrate/proxywasm/testdata/req-header-v1/go.sum
  test/integrate/proxywasm/testdata/req-header-v1/main.go
  test/integrate/proxywasm/testdata/req-header-v1/main.wasm
Labels: cla:yes, size/L, First-time contributor

#2166 golangci-lint skip dir pkg/mtls and module/http2
  .github/workflows/reviewdog.yml
Labels: cla:yes, size/XS

#2167 run golangci only when pull request
  .github/workflows/reviewdog.yml
Labels: cla:yes, size/XS, question

#2169 Fixes proxywasm test which accidentally used v2 imports
  go.mod
  go.sum
  test/integrate/proxywasm/proxywasm_test.go
  test/integrate/proxywasm/testdata/req-header-v1/go.mod
  test/integrate/proxywasm/testdata/req-header-v1/go.sum
  test/integrate/proxywasm/testdata/req-header-v1/main.go
  test/integrate/proxywasm/testdata/req-header-v1/main.wasm
Labels: cla:yes, size/M

#2170 bugfix: LB_ORIGINAL_DST retryTime is 0
  pkg/filter/network/streamproxy/streamproxy.go
Labels: cla:yes, size/XS

#2171 feat: support useOriginalDst passthrough
  istio/istio1106/xds/conv/convert_listener.go
  istio/istio1106/xds/conv/convert_listener_test.go
Labels: cla:yes, size/L

#2180 1、修复 connpool_binging 在连接 upstream timeout 时出现的 panic 问题
  pkg/stream/xprotocol/connpool_binding.go
Labels: cla:yes, size/XS

#2172 Moves to consolidated proxy-wasm implementation and enables wazero by default
  Makefile
  cmd/mosn/main/mosn.go
  examples/codes/trace/skywalking-plugin/http/main/mosn.go
  go.mod
  go.sum
  pkg/filter/stream/proxywasm/filter_test.go
  pkg/mock/wasm.go
  pkg/types/wasm.go
  pkg/wasm/abi/proxywasm010/factory.go
  pkg/wasm/abi/proxywasm020/factory.go
  pkg/wasm/abi/proxywasm020/imports_test.go
  pkg/wasm/runtime/wasmer/debug.go
  pkg/wasm/runtime/wasmer/instance.go
  pkg/wasm/runtime/wasmer/instance_test.go
  pkg/wasm/runtime/wasmer/module.go
  pkg/wasm/runtime/wasmer/testdata/data.wasm
  pkg/wasm/runtime/wasmer/types.go
  pkg/wasm/runtime/wasmer/wasmer_supported.go
  pkg/wasm/runtime/wasmer/wasmer_unsupported.go
  pkg/wasm/runtime/wazero/wazero.go
  test/integrate/proxywasm/proxywasm_test.go
  test/integrate/proxywasm/proxywasm_wasmer_test.go
  test/integrate/proxywasm/proxywasm_wazero_test.go
  test/integrate/wasmproxy_test.go
Labels: cla:yes, size/XXL

#2173 test: add benchmark
  Makefile
  test/benchmark/benchmark-shell.sh
  test/benchmark/mosn_benchmark.json
Labels: cla:yes, size/L

#2119 optimze: reuse subset entry to optimze alloc/inuse memory
  pkg/upstream/cluster/subset_loadbalancer_builder.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: cla:yes, size/M

#2188 fix hashcode
  pkg/upstream/cluster/subset_loadbalancer_builder.go
Labels: cla:yes, bug, size/XS, First-time contributor

#2190 fix print error
  examples/codes/xprotocol_with_goplugin_example/codec/decoder.go
Labels: cla:yes, bug, size/XS

#2182 bugfix: Modify the way xds listener logs are parsed
  istio/istio1106/xds/conv/convert_listener.go
  istio/istio1106/xds/conv/convert_listener_test.go
Labels: cla:yes, size/L

#2193 bugfix: smooth upgrade failed patch
  pkg/mosn/mosn.go
  pkg/stagemanager/stage_manager.go
  pkg/stagemanager/stage_manager_test.go
Labels: cla:yes, size/S
