Repository mosn/mosn, pull requests merged in 2022-10, with the labels that each got.

#2124 Metrics plugin
  go.mod
  go.sum
  pkg/metrics/store.go
  pkg/types/metrics.go
Labels: cla:yes, size/M

#2149 chore: go mod tidy
  go.sum
Labels: cla:yes, size/XS

#2122 chore: removed outdated comment.
  pkg/proxy/retrystate.go
Labels: cla:yes, size/XS

#2142 feat: transparent proxy
  examples/cn_readme/tproxy/tproxy_egress/README.md
  examples/cn_readme/tproxy/tproxy_ingress/README.md
  examples/codes/tproxy/tproxy_egress/cleanup.sh
  examples/codes/tproxy/tproxy_egress/config.json
  examples/codes/tproxy/tproxy_egress/iptables_config.sh
  examples/codes/tproxy/tproxy_egress/setup.sh
  examples/codes/tproxy/tproxy_ingress/cleanup.sh
  examples/codes/tproxy/tproxy_ingress/config.json
  examples/codes/tproxy/tproxy_ingress/iptables_config.sh
  examples/codes/tproxy/tproxy_ingress/setup.sh
  istio/_istio152/xds/conv/convertxds.go
  istio/istio1106/xds/conv/convert_listener.go
  pkg/config/v2/server.go
  pkg/config/v2/upstream.go
  pkg/filter/listener/originaldst/factory.go
  pkg/filter/listener/originaldst/originaldst.go
  pkg/filter/network/tunnel/backend_connection.go
  pkg/filter/network/tunnel/connection.go
  pkg/mock/upstream.go
  pkg/network/connection.go
  pkg/network/listener.go
  pkg/network/transfer.go
  pkg/network/udpreceiver.go
  pkg/server/handler.go
  pkg/stream/http/connpool_test.go
  pkg/stream/xprotocol/mock_test.go
  pkg/types/network.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/host.go
  test/cases/tproxy/cleanup.sh
  test/cases/tproxy/iptables_config.sh
  test/cases/tproxy/setup.sh
  test/cases/tproxy/tproxy_test.go
Labels: cla:yes, size/XL

#2154 update api and pkg version to 1.2.1
  go.mod
  go.sum
Labels: cla:yes, size/S

#2151 release version v1.2.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/1.2.0.md
Labels: cla:yes, size/L

#2161 Fix some problems in the README.md
  examples/cn_readme/xprotocol_with_goplugin_example/README.md
Labels: cla:yes, bug, size/XS, First-time contributor
