Repository mosn/mosn, pull requests merged in 2022-05, with the labels that each got.

#2029 fix: should allow AppendGracefulStopStage when mosn is starting or running.
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, size/M

#2031 go.mod: update mosn.io/pkg and mosn.io/api to v1.0.0.
  go.mod
  go.sum
Labels: cla:yes, size/S

#2032 release v1.0.1.
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
Labels: cla:yes, size/S

#2033 [Example] fix wasm example tinygo/tinygo-dev image version
  examples/codes/wasm/http/README_CN.md
  examples/codes/wasm/http/README_EN.md
  examples/codes/wasm/http/makefile
  examples/codes/wasm/httpCall/makefile
  examples/codes/wasm/sofarpc/README_CN.md
  examples/codes/wasm/sofarpc/README_EN.md
  examples/codes/wasm/sofarpc/makefile
Labels: cla:yes, bug, size/S

#2010 optimize build subset loadbalancer by bitmap
  pkg/mock/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/lb_register_test.go
  pkg/upstream/cluster/subset_loadbalancer_builder.go
  pkg/upstream/cluster/subset_loadbalancer_builder_test.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: cla:yes, size/XL

#2034 fix: stm.SetState before logger.CloseAll, otherwise, the log in SetState will lost.
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, bug, size/XS
