Repository mosn/mosn, pull requests merged in 2022-07, with the labels that each got.

#2057 fix typos
  cmd/mosn/main/control.go
  examples/codes/sofarpc-with-xprotocol-sample/client.go
  examples/codes/tcpproxy-sample/rpc_client.go
  examples/codes/tunnel-sample/client.go
  istio/_istio152/main/control.go
  istio/istio1106/istio/control/http/attributes_builder.go
  istio/istio1106/main/control.go
  istio/istio1106/xds/ads_config.go
  istio/istio1106/xds/client.go
  istio/istio1106/xds/conv/convert_cluster.go
  istio/istio1106/xds/conv/update.go
  pkg/configmanager/dump_action.go
  pkg/filter/stream/dubbo/dubbo.go
  pkg/mosn/default_stages.go
  pkg/mosn/mosn.go
  pkg/mtls/sds/subscriber.go
  pkg/protocol/xprotocol/dubbo/metadata.go
  pkg/protocol/xprotocol/registry.go
  pkg/protocol/xprotocol/tars/protocol.go
  pkg/protocol/xprotocol/wasm/hijacker.go
  pkg/proxy/downstream.go
  pkg/router/configutility.go
  pkg/router/routers_impl.go
  pkg/router/routers_manager.go
  pkg/router/rpc_rule.go
  pkg/router/types.go
  pkg/server/adapter.go
  pkg/server/handler.go
  pkg/stagemanager/stage_manager.go
  pkg/stream/http/buffer.go
  pkg/stream/http/connpool.go
  pkg/stream/http/stream.go
  pkg/stream/http2/stream.go
  pkg/stream/xprotocol/keepalive_configure.go
  pkg/stream/xprotocol/mock_test.go
  pkg/types/healthcheck.go
  pkg/types/network.go
  pkg/types/route.go
  pkg/types/stream.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/cluster/edf.go
  pkg/upstream/cluster/health.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/tls.go
  pkg/upstream/healthcheck/factory.go
  pkg/upstream/servicediscovery/dubbod/notify.go
  pkg/upstream/servicediscovery/dubbod/pub.go
  pkg/upstream/servicediscovery/dubbod/structs.go
  pkg/upstream/servicediscovery/dubbod/sub.go
  pkg/variable/protocolres.go
  pkg/wasm/plugin.go
  test/lib/factory.go
  test/util/xprotocol_rpc.go
Labels: cla:yes, bug, size/L

#2066 log while parse http request error
  pkg/stream/http/stream.go
Labels: cla:yes, size/XS

#2070 Fix spelling error for `matcher` #2069
  pkg/filter/stream/transcoder/config.go
  pkg/filter/stream/transcoder/http2bolt/http2bolt_simple_test.go
  pkg/filter/stream/transcoder/matcher/config.go
  pkg/filter/stream/transcoder/matcher/factory.go
  pkg/filter/stream/transcoder/matcher/transcoder_matches.go
  pkg/filter/stream/transcoder/simplematcher/simple_matcher_test.go
  pkg/router/routers_impl_test.go
  pkg/router/rpc_rule.go
Labels: cla:yes, bug, size/M, First-time contributor

#2071 Update license-checker.yml
  .github/workflows/license-checker.yml
Labels: cla:yes, size/XS, First-time contributor

#2062 修复协议转换的 panic 问题
  pkg/filter/stream/transcoder/README.md
  pkg/filter/stream/transcoder/filter.go
Labels: cla:yes, size/M

#2047 Tracer plugin
  examples/cn_readme/trace/skywalking-plugin/http/README.md
  examples/codes/trace/skywalking-plugin/http/client.go
  examples/codes/trace/skywalking-plugin/http/config.json
  examples/codes/trace/skywalking-plugin/http/main/control.go
  examples/codes/trace/skywalking-plugin/http/main/mosn.go
  examples/codes/trace/skywalking-plugin/http/server.go
  examples/codes/trace/skywalking-plugin/http/skywalking-docker-compose.yaml
  examples/codes/trace/skywalking-plugin/plugins/config.go
  examples/codes/trace/skywalking-plugin/plugins/span.go
  examples/codes/trace/skywalking-plugin/plugins/tracer.go
  pkg/trace/driver_plugin.go
  pkg/trace/driver_plugin_test.go
Labels: cla:yes, size/XXL

#2082 [bugfix] add connection event listener after ac.element set to avoid panic
  pkg/server/handler.go
Labels: cla:yes, size/S

#2061 同步develop分支改动到master分支
  pkg/types/loadbalancer.go
  pkg/upstream/cluster/cluster_test.go
  pkg/upstream/cluster/subset_loadbalancer.go
  pkg/upstream/cluster/subset_loadbalancer_test.go
Labels: cla:yes, size/M

#2088 [chore] add SetConfig for tls.Conn
  pkg/mtls/crypto/README
  pkg/mtls/crypto/tls/tls_custom.go
Labels: cla:yes, size/XS
