Repository mosn/mosn, pull requests merged in 2022-03, with the labels that each got.

#1970 fix: undefined behavior when weight out of range
  istio/istio152/xds/conv/convertxds.go
  istio/istio152/xds/conv/convertxds_test.go
  pkg/config/v2/constants.go
  pkg/configmanager/parser.go
  pkg/configmanager/parser_test.go
  pkg/upstream/cluster/edf.go
  pkg/upstream/cluster/edf_test.go
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, bug, size/L, question

#1922 feature: introduce a new XProtocol interface GracefulShutdown for graceful stop existing connections.
  cmd/mosn/main/control.go
  examples/codes/xprotocol_with_goplugin_example/codec/command.go
  examples/codes/xprotocol_with_goplugin_example/codec/protocol.go
  go.mod
  go.sum
  pkg/mock/stm_app.go
  pkg/module/http2/mhttp2.go
  pkg/mosn/init.go
  pkg/mosn/mosn.go
  pkg/network/idlechecker_test.go
  pkg/network/listener.go
  pkg/network/listener_test.go
  pkg/protocol/xprotocol/example/command.go
  pkg/protocol/xprotocol/example/decoder.go
  pkg/protocol/xprotocol/example/protocol.go
  pkg/proxy/proxy.go
  pkg/server/adapter.go
  pkg/server/adapter_test.go
  pkg/server/handler.go
  pkg/server/reconfigure.go
  pkg/server/server.go
  pkg/server/types.go
  pkg/stagemanager/stage_manager.go
  pkg/stagemanager/stage_manager_test.go
  pkg/stream/http2/stream.go
  pkg/stream/xprotocol/conn.go
  pkg/stream/xprotocol/connpool.go
  pkg/stream/xprotocol/connpool_multiplex.go
  pkg/stream/xprotocol/factory.go
  pkg/types/network.go
  test/cases/run_all.sh
  test/cases/shutdown/http2_test.go
  test/cases/shutdown/xprotocol_example_test.go
  test/lib/mosn/mosn.go
  vendor/modules.txt
  vendor/mosn.io/api/network.go
  vendor/mosn.io/api/xprotocol.go
  vendor/mosn.io/pkg/utils/sync_list.go
Labels: cla:yes, size/XXL

#1975 Export Mosn.isFromUpgrade
  pkg/mosn/init.go
  pkg/mosn/mosn.go
Labels: cla:yes, size/XS

#1976 allow the setting of stm.state, used for unit-test
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, size/XS

#1972 [Feature] Add Variable for Storing XProtocol Req/Resp Raw Data
  pkg/protocol/xprotocol/bolt/decoder.go
  pkg/protocol/xprotocol/boltv2/decoder.go
  pkg/protocol/xprotocol/dubbo/decoder.go
  pkg/protocol/xprotocol/dubbothrift/decoder.go
  pkg/protocol/xprotocol/tars/decoder.go
  pkg/protocol/xprotocol/var.go
  pkg/types/variable.go
Labels: cla:yes, size/M

#1981 fix: add nil check for listener. setDeadline
  pkg/network/listener.go
Labels: cla:yes, bug, size/S

#1980 fix: typing error
  pkg/upstream/cluster/cluster_manager.go
Labels: cla:yes, bug, size/XS, First-time contributor

#1988 style:fix typos
  cmd/mosn/main/control.go
  pkg/mosn/mosn.go
  pkg/stagemanager/stage_manager.go
Labels: cla:yes, bug, size/S, First-time contributor

#1898 fix race unit test error #1897
  pkg/upstream/cluster/loadbalancer_test.go
Labels: cla:yes, bug, size/M
