Repository mosn/mosn, pull requests merged in 2023-01, with the labels that each got.

#2210 Synchronize #2199 modifications to istio1106
  istio/istio1106/xds/conv/update.go
Labels: cla:yes, size/XS

#2200 integrate with mosn.io/envoy-go-extension
  Makefile
  cmd/moe/main/control.go
  cmd/moe/main/mosn.go
  configs/mosn_so.json
  examples/codes/envoy-go-extension/Makefile
  examples/codes/envoy-go-extension/README_CN.md
  examples/codes/envoy-go-extension/README_EN.md
  examples/codes/envoy-go-extension/envoy.yaml
  examples/codes/envoy-go-extension/filter.go
  examples/codes/envoy-go-extension/mosn.json
  examples/codes/envoy-go-extension/server.go
  go.mod
  go.sum
  pkg/moe/buffer.go
  pkg/moe/filtermanager.go
  pkg/moe/stream.go
  pkg/moe/type.go
  pkg/moe/var.go
Labels: cla:yes, size/XXL

#2216 refactor: pprof import add in mosn package
  cmd/moe/main/control.go
  cmd/mosn/main/control.go
  examples/codes/trace/skywalking-plugin/http/main/control.go
  istio/_istio152/main/control.go
  istio/istio1106/main/control.go
  pkg/mosn/init.go
Labels: cla:yes, size/XS

#2222 fix: moe cmd args problem
  cmd/moe/main/mosn.go
Labels: cla:yes, bug, size/S

#2221 [bugfix]: metrics exclusionLabels and exclusionKeys not working for static config
  pkg/mosn/default_stages.go
  pkg/mosn/init.go
  pkg/mosn/mosn.go
Labels: cla:yes, size/M
