Repository mosn/mosn, pull requests merged in 2023-02, with the labels that each got.

#2228 [bugfix] init seperate rander for every health checker
  pkg/upstream/healthcheck/healthchecker.go
Labels: cla:yes, size/XS

#2225 [Bugfix] Rewrite upstream request protocol to HTTP1.1
  pkg/stream/http/stream.go
Labels: cla:yes, size/XS

#2197 Allow Setting Cluster Idle Timeout to Zero to Indicate Never Timeout
  pkg/upstream/cluster/host.go
  pkg/upstream/cluster/host_test.go
Labels: cla:yes

#2215 bugfix: Completing the missing statistics
  pkg/filter/network/streamproxy/streamproxy.go
  pkg/stream/http/connpool.go
  pkg/stream/http2/connpool.go
Labels: cla:yes, bug, size/M

#2212 release version v1.4.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/1.4.0.md
Labels: cla:yes, size/L

#2245 doc: update partners & users.
  README.md
  README_ZH.md
Labels: cla:yes, size/L
