Repository mosn/mosn, pull requests merged in 2023-04, with the labels that each got.

#2281 feat: support cluster exclusive connectionPool
  pkg/config/v2/upstream.go
  pkg/mock/upstream.go
  pkg/mosn/mosn.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/cluster_manager.go
  pkg/upstream/cluster/cluster_manager_test.go
Labels: cla:yes, size/L, First-time contributor

#2288 ci: the Go version is decided by the image used in the CI
  .github/workflows/reviewdog.yml
  Makefile
  go.mod
Labels: cla:yes, size/S, First-time contributor

#2174 bugfix: incorrectly assume the variable not found if the real value is '-'
  pkg/log/accesslog_test.go
  pkg/proxy/var.go
  pkg/proxy/var_test.go
  pkg/stream/http/var.go
  pkg/stream/http/var_test.go
  pkg/stream/http2/var.go
  pkg/stream/http2/var_test.go
Labels: cla:yes, size/L

#2284 bugfix: the interface appears in the configuration
  istio/_istio152/xds/conv/convertxds.go
  istio/istio1106/xds/conv/convert_cluster.go
  pkg/config/v2/loadbalancer.go
  pkg/config/v2/unmarshal_test.go
  pkg/config/v2/upstream.go
  pkg/mock/upstream.go
  pkg/types/upstream.go
  pkg/upstream/cluster/cluster.go
  pkg/upstream/cluster/lb_leastconnection.go
  pkg/upstream/cluster/loadbalancer.go
Labels: cla:yes, size/M

#2286 feat: `LeastActiveRequest` (and `LeastActiveConnection`) supports setting the bias of active request metric
  istio/istio1106/xds/conv/convert_cluster.go
  pkg/config/v2/loadbalancer.go
  pkg/upstream/cluster/lb_leastconnection.go
  pkg/upstream/cluster/loadbalancer.go
Labels: cla:yes, size/M

#2253 feat: PeakEWMA load balancer
  go.mod
  go.sum
  pkg/config/v2/config.go
  pkg/metrics/ewma/ewma.go
  pkg/metrics/ewma/ewma_test.go
  pkg/metrics/store.go
  pkg/metrics/store_lazy.go
  pkg/metrics/upstream.go
  pkg/mosn/mosn.go
  pkg/proxy/gomock_test.go
  pkg/proxy/proxy_downstream_test.go
  pkg/proxy/upstream.go
  pkg/types/loadbalancer.go
  pkg/types/upstream.go
  pkg/upstream/cluster/edf_test.go
  pkg/upstream/cluster/lb_leastconnection.go
  pkg/upstream/cluster/loadbalancer.go
  pkg/upstream/cluster/loadbalancer_test.go
  pkg/upstream/cluster/stats.go
Labels: cla:yes, size/XL

#2277 release version v1.5.0
  CHANGELOG.md
  CHANGELOG_ZH.md
  VERSION
  reports/1.5.0.md
Labels: cla:yes, size/L

#2226 Update example server and client config file in README
  examples/en_readme/http-sample/README.md
Labels: cla:yes, size/XS, First-time contributor
